jpsType: install
jpsVersion: '1.7.4'

name: Infra/Decidim
id: decidim-vanilla-infra
description:
  short: Decidim Saas
categories:
  - apps/platforms
baseUrl: https://raw.githubusercontent.com/octree-gva/voca-jps/main
logo: assets/decidim_logo.png
ssl: true
ha: false
envGroups: "vocacity"

globals:
  DB_PASSWORD: "${fn.password(32)}"
  DB_USER: "decidim_${fn.password(6)}"
  APP_SESSION_KEY: "${fn.password(16)}"
  SECRET_KEY_BASE: "${fn.password(128)}"
  MASTER_KEY: "${fn.password(32)}"
  REDIS_USER: "admin_${fn.password(6)}"
  REDIS_PASSWORD: "${fn.password(64)}"
  DECIDIM_DEFAULT_SYSTEM_PASSWORD: "${fn.password(32)}"

settings:
  fields:
  - name: PUBLIC_URL
    type: string
    caption: PUBLIC_URL
  - name: TRAEFIK_ENVNAME
    type: string
    caption: TRAEFIK_ENVNAME
    default: vocacity-traefik
  - name: PUBLIC_DOMAIN
    type: string
    caption: PUBLIC_DOMAIN
  - name: ADMIN_EMAIL
    type: string
    caption: ADMIN_EMAIL
  - name: DECIDIM_DEFAULT_SYSTEM_EMAIL
    caption: DECIDIM_DEFAULT_SYSTEM_EMAIL
    type: string
  - name: DECIDIM_NAME
    caption: DECIDIM_NAME
    type: string
  - name: DECIDIM_SHORTNAME
    caption: DECIDIM_SHORTNAME
    type: string
  - name: DECIDIM_DEFAULT_LOCALE
    caption: DECIDIM_DEFAULT_LOCALE
    type: string
  - name: DECIDIM_AVAILABLE_LOCALES
    caption: DECIDIM_AVAILABLE_LOCALES
    type: string
  - name: DECIDIM_CURRENCY_UNIT
    caption: DECIDIM_CURRENCY_UNIT
    type: string
  - name: JOB_IMAGE_REGISTRY
    type: string
    caption: JOB_IMAGE_REGISTRY
  - type: string
    name: JOB_IMAGE_PAGE
    caption: JOB_IMAGE_PAGE
  - type: string
    name: PROD_IMAGE_REGISTRY
    caption: PROD_IMAGE_REGISTRY
  - type: string
    name: PROD_IMAGE_PATH
    caption: PROD_IMAGE_PATH
  - name: IMAGE_USERNAME
    caption: IMAGE_USERNAME
    type: string
  - name: IMAGE_PASSWORD
    caption: IMAGE_PASSWORD
    type: string
  - type: string
    name: TIMEZONE
    caption: TIMEZONE
  - type: string
    name: ERROR_URL
    caption: ERROR_URL
  - type: string
    name: WEBHOOK_URL
    caption: WEBHOOK_URL
  - type: string
    name: WEBHOOK_HMAC
    caption: WEBHOOK_HMAC
  - type: string
    name: INSTANCE_UUID
    caption: INSTANCE_UUID
  - name: SMTP_HOST
    caption: SMTP_HOST
    type: string
  - name: SMTP_DOMAIN
    caption: SMTP_DOMAIN
    type: string
  - name: SMTP_PORT
    caption: SMTP_PORT
    type: string
  - name: SMTP_USERNAME
    caption: SMTP_USERNAME
    type: string
  - name: SMTP_PASSWORD
    caption: SMTP_PASSWORD
    type: string
  - type: string
    name: SMTP_AUTHENTICATION
    caption: SMTP_AUTHENTICATION
  - type: string
    name: SMTP_HELO_DOMAIN
    caption: SMTP_HELO_DOMAIN
  - type: string
    name: SMTP_OPEN_TIMEOUT
    caption: SMTP_OPEN_TIMEOUT
  - type: string
    name: SMTP_READ_TIMEOUT
    caption: SMTP_READ_TIMEOUT
  - type: string
    name: BACKUP_CYPHER_KEY
    caption: BACKUP_CYPHER_KEY
  - type: string
    name: BACKUP_CYPHER_IV
    caption: BACKUP_CYPHER_IV

nodes:
- displayName: NGinx
  fixedCloudlets: 3
  flexibleCloudlets: 16
  diskLimit: 5G
  nodeGroup: bl
  nodeType: nginx-dockerized
  tag: 1.20.2
  volumes:
  - /public
  - /etc/nginx/nginx-jelastic.conf
  - /etc/jelastic/redeploy.conf
  volumeMounts:
    /public:
      protocol: NFS4
      readOnly: true
      sourceNodeGroup: storage
      sourcePath: "/data"
  links:
  - cp:app

# Decidim application
- displayName: Decidim
  fixedCloudlets: 3
  flexibleCloudlets: 8
  diskLimit: 100G
  count: 1
  env:
    APP_SESSION_KEY: "${globals.APP_SESSION_KEY}"
    INSTANCE_UUID: "${settings.INSTANCE_UUID}"
    DATABASE_HOST: psql
    DATABASE_PASSWORD: "${globals.DB_PASSWORD}"
    DATABASE_DATABASE: decidim
    DATABASE_USERNAME: "${globals.DB_USER}"
    DATABASE_URL: postgres://${globals.DB_USER}:${globals.DB_PASSWORD}@psql:5432/decidim
    SECRET_KEY_BASE: "${globals.SECRET_KEY_BASE}"
    MASTER_KEY: "${globals.MASTER_KEY}"
    SMTP_ADDRESS: "${settings.SMTP_HELO_DOMAIN}"
    BACKUP_CYPHER_KEY: "${settings.BACKUP_CYPHER_KEY}"
    BACKUP_CYPHER_IV: "${settings.BACKUP_CYPHER_IV}"
    SMTP_AUTHENTICATION: "${settings.SMTP_AUTHENTICATION}"
    SMTP_DOMAIN: "${settings.SMTP_DOMAIN}"
    SMTP_USERNAME: "${settings.SMTP_USERNAME}"
    SMTP_PASSWORD: "${settings.SMTP_PASSWORD}"
    SMTP_PORT: "${settings.SMTP_PORT}"
    SMTP_STARTTLS_AUTO: true
    RAILS_FORCE_SSL: "disabled"
    RAILS_CACHE_MODE: "redis"
    RAILS_CACHE_REDIS_URL: "redis://default:${globals.REDIS_PASSWORD}@redis:6379/0"
    RAILS_JOB_MODE: "sidekiq"
    JOB_REDIS_URL: "redis://default:${globals.REDIS_PASSWORD}@redis:6379/1"
    TZ: "${settings.TIMEZONE}"
    DECIDIM_CURRENCY_UNIT: "${settings.DECIDIM_CURRENCY_UNIT}"
    DECIDIM_DEFAULT_LOCALE: ${settings.DECIDIM_DEFAULT_LOCALE}
    DECIDIM_AVAILABLE_LOCALES: ${settings.DECIDIM_AVAILABLE_LOCALES}

  links:
  - sqldb:psql
  - nosqldb:redis
  image: "${settings.PROD_IMAGE_PATH}"
  registry:
    url: "${settings.PROD_IMAGE_REGISTRY}"
    user: "${settings.IMAGE_USERNAME}"
    password: "${settings.IMAGE_PASSWORD}"
  nodeGroup: cp
  isSLBAccessEnabled: false
  volumes:
  - /home/decidim/app/public
  volumeMounts:
    /home/decidim/app/public:
      protocol: NFS4
      readOnly: false
      sourceNodeGroup: storage
      sourcePath: "/data"

# Decidim runner (sidekiq+tasks)
- displayName: Sidekiq/Tasks
  fixedCloudlets: 4
  flexibleCloudlets: 30 # needed for compilation time. 
  diskLimit: 5G
  env:
    APP_SESSION_KEY: "${globals.APP_SESSION_KEY}"
    INSTANCE_UUID: "${settings.INSTANCE_UUID}"
    DATABASE_HOST: psql
    DATABASE_PASSWORD: "${globals.DB_PASSWORD}"
    DATABASE_DATABASE: decidim
    DATABASE_USERNAME: "${globals.DB_USER}"
    DATABASE_URL: postgres://${globals.DB_USER}:${globals.DB_PASSWORD}@psql:5432/decidim
    SECRET_KEY_BASE: "${globals.SECRET_KEY_BASE}"
    SMTP_ADDRESS: "${settings.SMTP_HELO_DOMAIN}"
    SMTP_AUTHENTICATION: "${settings.SMTP_AUTHENTICATION}"
    SMTP_DOMAIN: "${settings.SMTP_DOMAIN}"
    SMTP_USERNAME: "${settings.SMTP_USERNAME}"
    SMTP_PASSWORD: "${settings.SMTP_PASSWORD}"
    SMTP_PORT: "${settings.SMTP_PORT}"
    RAILS_FORCE_SSL: "disabled"
    RAILS_CACHE_MODE: "redis"
    RAILS_CACHE_REDIS_URL: "redis://default:${globals.REDIS_PASSWORD}@redis:6379/0"
    RAILS_JOB_MODE: "sidekiq"
    JOB_REDIS_URL: "redis://default:${globals.REDIS_PASSWORD}@redis:6379/1"
    SMTP_STARTTLS_AUTO: true
    TZ: "${settings.TIMEZONE}"
    DOCKER_EXPOSED_PORT: 3000
    PORT: 3000
    WEBHOOK_PASSWORD: "${settings.WEBHOOK_PASSWORD}"
    WEBHOOK_USERNAME: "${settings.WEBHOOK_USERNAME}"
    WEBHOOK_URL: "${settings.WEBHOOK_URL}"
    WEBHOOK_HMAC: "${settings.WEBHOOK_HMAC}"
    DECIDIM_HOST: "${settings.PUBLIC_DOMAIN}"
    DECIDIM_URL: "${settings.PUBLIC_URL}"
    DECIDIM_CURRENCY_UNIT: "${settings.DECIDIM_CURRENCY_UNIT}"
    DECIDIM_DEFAULT_LOCALE: ${settings.DECIDIM_DEFAULT_LOCALE}
    DECIDIM_AVAILABLE_LOCALES: ${settings.DECIDIM_AVAILABLE_LOCALES}
  links:
  - sqldb:psql
  - nosqldb:redis
  isSLBAccessEnabled: false
  image: "${settings.JOB_IMAGE_PAGE}"
  registry:
    url: "${settings.JOB_IMAGE_REGISTRY}"
    user: "${settings.IMAGE_USERNAME}"
    password: "${settings.IMAGE_PASSWORD}"
  nodeGroup: vocacity
  volumes:
  - /home/decidim/app/public
  volumeMounts:
    /home/decidim/app/public:
      protocol: NFS4
      readOnly: false
      sourceNodeGroup: storage
      sourcePath: "/data"

# DATA : postgres database
- displayName: PG
  fixedCloudlets: 3
  flexibleCloudlets: 12
  diskLimit: 100G
  nodeGroup: sqldb
  image: postgres:12
  isSLBAccessEnabled: false
  env:
    POSTGRES_PASSWORD: "${globals.DB_PASSWORD}"
    POSTGRES_DB: decidim
    POSTGRES_USER: "${globals.DB_USER}"
    TZ: "${settings.TIMEZONE}"
    PGTZ: "${settings.TIMEZONE}"
    ADMINPANEL_ENABLED: false
    LC_ALL: "en_US.UTF-8"
  volumes:
  - "/var/lib/postgresql/data"

- displayName: Redis 
  image: jelastic/redis:6.2.6
  fixedCloudlets: 2
  flexibleCloudlets: 16
  nodeGroup: nosqldb
  isSLBAccessEnabled: false
  env:
    ADMINPANEL_ENABLED: false

# DATA : shared public folder
- displayName: Shared Files
  cloudlets: 2
  diskLimit: 100G
  nodeGroup: storage
  nodeType: storage
  tag: 2.0-9.4
  isSLBAccessEnabled: false
  env:
    HOME_DIR: "/data"
  volumes:
  - /data
  
onInstall: 
  - setupRedisPassword
  - wakeUpTraefik
  - seedDatabase
  - decidimProxy
  - restartNodes:
      nodeType: bl
  - openTraefik
  - wakeUpTraefik

actions:
  setupRedisPassword:
    - cmd[nosqldb]: jem passwd set -p ${globals.REDIS_PASSWORD}
    - cmd[nosqldb]: echo "time=\"$(date +%FT%TZ)\" level=info msg=\"Redis password changed\"" >> /var/log/run.log
  wakeUpTraefik: 
    - cmd[vocacity]: curl -k ${settings.PUBLIC_DOMAIN}
  seedDatabase:
    - install:
      jps: scripts/deploy/seed.yml?_r=${fn.random}
      envName: ${env.envName}
      loggerName: "Decidim-Migration"
      settings:
        ADMIN_EMAIL: ${settings.ADMIN_EMAIL}
        DECIDIM_HOST: ${settings.PUBLIC_DOMAIN}
        DECIDIM_URL: ${settings.PUBLIC_URL}
        DECIDIM_DEFAULT_SYSTEM_EMAIL: ${settings.ADMIN_EMAIL}
        DECIDIM_DEFAULT_SYSTEM_PASSWORD: ${globals.DECIDIM_DEFAULT_SYSTEM_PASSWORD}
        DECIDIM_NAME: ${settings.DECIDIM_NAME}
        DECIDIM_SHORTNAME: ${settings.DECIDIM_SHORTNAME}
        DECIDIM_DEFAULT_LOCALE: ${settings.DECIDIM_DEFAULT_LOCALE}
        DECIDIM_AVAILABLE_LOCALES: ${settings.DECIDIM_AVAILABLE_LOCALES}
  decidimProxy:
    - install:
      jps: scripts/deploy/nginx-conf.yml?_r=${fn.random}
      envName: ${env.envName}
      loggerName: "Decidim-Nginx"
      settings:
        DECIDIM_URL: ${settings.PUBLIC_URL}
