onBeforeInit: return settings;

fields:
  - name: TRAEFIK_ENVNAME
    type: string
    caption: TRAEFIK_ENVNAME
    default: vocacity-traefik
  - name: IMAGE_REGISTRY
    type: string
    caption: IMAGE_REGISTRY
  - type: string
    name: IMAGE_PATH
    caption: IMAGE_PATH
  - name: IMAGE_USERNAME
    caption: IMAGE_USERNAME
    type: string
  - name: IMAGE_PASSWORD
    caption: IMAGE_PASSWORD
    type: string
  - type: string
    name: ERROR_URL
    caption: ERROR_URL
  - type: string
    name: WEBHOOK_URL
    caption: WEBHOOK_URL
  - type: string
    name: WEBHOOK_HMAC
    caption: WEBHOOK_HMAC
  - type: string
    name: INSTANCE_UUID
    caption: INSTANCE_UUID
  - name: SERVICE_HOST_NAME
    caption: Used for traefik directory
  - name: SMTP_HOST
    caption: SMTP_HOST
    type: string
  - name: SMTP_DOMAIN
    caption: SMTP_DOMAIN
    type: string
  - name: SMTP_PORT
    caption: SMTP_PORT
    type: string
  - name: SMTP_USERNAME
    caption: SMTP_USERNAME
    type: string
  - name: SMTP_PASSWORD
    caption: SMTP_PASSWORD
    type: string
  - type: string
    name: SMTP_AUTHENTICATION
    caption: SMTP_AUTHENTICATION
  - type: string
    name: SMTP_HELO_DOMAIN
    caption: SMTP_HELO_DOMAIN
  - type: string
    name: SMTP_OPEN_TIMEOUT
    caption: SMTP_OPEN_TIMEOUT
  - type: string
    name: SMTP_READ_TIMEOUT
    caption: SMTP_READ_TIMEOUT
