onBeforeInit: return settings;

fields:
  - name: PUBLIC_URL
    type: string
    caption: PUBLIC_URL
  - name: TIMEZONE
    type: string
    caption: TIMEZONE
  - name: PUBLIC_DOMAIN
    type: string
    caption: PUBLIC_DOMAIN
