onBeforeInit: return settings;

fields:
  - name: PUBLIC_URL
    type: string
    caption: PUBLIC_URL
  - name: TRAEFIK_ENVNAME
    type: string
    caption: TRAEFIK_ENVNAME
    default: vocacity-traefik
  - name: PUBLIC_DOMAIN
    type: string
    caption: PUBLIC_DOMAIN
  - name: ADMIN_EMAIL
    type: string
    caption: ADMIN_EMAIL
  - name: DECIDIM_DEFAULT_SYSTEM_EMAIL
    caption: DECIDIM_DEFAULT_SYSTEM_EMAIL
    type: string
  - name: DECIDIM_NAME
    caption: DECIDIM_NAME
    type: string
  - name: DECIDIM_SHORTNAME
    caption: DECIDIM_SHORTNAME
    type: string
  - name: DECIDIM_DEFAULT_LOCALE
    caption: DECIDIM_DEFAULT_LOCALE
    type: string
  - name: DECIDIM_AVAILABLE_LOCALES
    caption: DECIDIM_AVAILABLE_LOCALES
    type: string
  - name: DECIDIM_CURRENCY_UNIT
    caption: DECIDIM_CURRENCY_UNIT
    type: string
  - name: JOB_IMAGE_REGISTRY
    type: string
    caption: JOB_IMAGE_REGISTRY
  - type: string
    name: JOB_IMAGE_PATH
    caption: JOB_IMAGE_PATH
  - type: string
    name: PROD_IMAGE_REGISTRY
    caption: PROD_IMAGE_REGISTRY
  - type: string
    name: PROD_IMAGE_PATH
    caption: PROD_IMAGE_PATH
  - name: IMAGE_USERNAME
    caption: IMAGE_USERNAME
    type: string
  - name: IMAGE_PASSWORD
    caption: IMAGE_PASSWORD
    type: string
  - type: string
    name: TIMEZONE
    caption: TIMEZONE
  - type: string
    name: ERROR_URL
    caption: ERROR_URL
  - type: string
    name: WEBHOOK_URL
    caption: WEBHOOK_URL
  - type: string
    name: WEBHOOK_HMAC
    caption: WEBHOOK_HMAC
  - type: string
    name: INSTANCE_UUID
    caption: INSTANCE_UUID
  - name: SMTP_HOST
    caption: SMTP_HOST
    type: string
  - name: SMTP_DOMAIN
    caption: SMTP_DOMAIN
    type: string
  - name: SMTP_PORT
    caption: SMTP_PORT
    type: string
  - name: SMTP_USERNAME
    caption: SMTP_USERNAME
    type: string
  - name: SMTP_PASSWORD
    caption: SMTP_PASSWORD
    type: string
  - type: string
    name: SMTP_AUTHENTICATION
    caption: SMTP_AUTHENTICATION
  - type: string
    name: SMTP_HELO_DOMAIN
    caption: SMTP_HELO_DOMAIN
  - type: string
    name: SMTP_OPEN_TIMEOUT
    caption: SMTP_OPEN_TIMEOUT
  - type: string
    name: SMTP_READ_TIMEOUT
    caption: SMTP_READ_TIMEOUT
  - type: string
    name: BACKUP_CYPHER_KEY
    caption: BACKUP_CYPHER_KEY
  - type: string
    name: BACKUP_CYPHER_IV
    caption: BACKUP_CYPHER_IV
